server {
    listen 80;
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # Tenta achar o arquivo, se não achar (rota do React), devolve o index.html
        try_files $uri $uri/ /index.html;
    }
}
